version: '3'

services:
  php:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "PHP_VERSION=${PHP_VERSION:-7.3}"
    depends_on:
      - mongodb
      - mysql
    volumes:
      - coverage:/home/lib/coverage

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: unittest
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    logging:
      driver: none

  mongodb:
    container_name: mongodb
    image: "mongo:${MONGODB_VERSION:-latest}"
    ports:
      - 27017:27017
    logging:
      driver: none
